.travis.yml, alpenhorn/__init__.py, alpenhorn/acquisition.py, alpenhorn/archive.py, alpenhorn/auto_import.py, alpenhorn/client.py, alpenhorn/config.py, alpenhorn/db.py, alpenhorn/generic.py, alpenhorn/legacy/auto_import.py, alpenhorn/legacy/client.py, alpenhorn/legacy/hpss_callback.py, alpenhorn/legacy/service.py, alpenhorn/legacy/update.py, alpenhorn/logger.py, alpenhorn/storage.py, doc/conf.py, setup.py, test-requirements.txt, tests/test_acquisition_model.py, tests/test_archive_model.py, tests/test_client.py, tests/test_config.py, tests/test_import.py, tests/test_storage_model.py
A minimal porting of alpenhorn to support Python 3. Done using python-future (though doesn't need its compatibility library).
=> Python 3 port

alpenhorn/auto_import.py, alpenhorn/client.py, alpenhorn/config.py, alpenhorn/db.py, alpenhorn/extensions.py, alpenhorn/service.py, alpenhorn/update.py, alpenhorn/util.py, tests/docker/alpenhorn.conf, tests/docker/test_docker.py, tests/test_client.py, tests/test_config.py, tests/test_extensions.py
This major set of changes brings back the ability of alpenhorn to actually manage an archive!
Major changes:
- Added a minimally modified version of the update loop code
(excluding HPSS support).
- Added back in the setup code for auto_import. With a few changes:
* The code now derives its cache of previously imported files from
the database.
* Only the filesystem pollng watchdog is used, as the code to
determine if the filesystem is local or network mounted is
sketchy.
- The client now starts a connection to the database and so is
functional again (in theory).
More minor changes and cleanups:
- Improved the configuration code with a better scheme for merging
config files.
- Fixed up the client tests to mock out the db connection/config
loading code.
- Changed verify command such that it …
=> Import and update loop

alpenhorn/acquisition.py, alpenhorn/auto_import.py, alpenhorn/client.py, tests/docker/test_docker.py, tests/fixtures/acquisition.yml, tests/test_acquisition_model.py, tests/test_archive_model.py, tests/test_client.py, tests/test_import.py
As planned this removes the concept of the instrument from the main alpenhorn code base.
=> Removed ArchiveInst

tests/docker/test_docker.py
Keep the docker environment alive after tests have run so that you can play around with it for fun (and profit).
Just run:
```
$ PLAYGROUND=yes py.test -s test_docker.py
```
=> Docker playground

alpenhorn/client.py, alpenhorn/update.py, tests/docker/test_docker.py, tests/test_client.py
Files marked as wants=M would not be selected by the clean command with the --now flag.
Please don't close my branch.
=> Bug with file selection in alpenhorn clean

alpenhorn/client.py, tests/test_client.py
Please review code for create group and create node
=> Alpenhorn dev

alpenhorn/client.py
=> Fix #35: correct the module containing `md5sum_file`

alpenhorn/client.py, tests/test_client.py
`client.import_files` has a number of built-in assumptions left over from the
old world of flat acquisitions, so it would not work properly when run from any
subdirectory of an arbitrarily nested structure (even subdirectories of an
acquisition).
This change implements the "natural" extension of the original `import_files`
design to Alpenhorn v2 directory structure. The starting directory can be inside
an acquisition or a parent directory of several acquisitions, but either way it
only considers for import files that are found by `os.walk` from that starting
point.
If `--acq` option is given, the walk is further restricted to only look at files
that would belong to those acquisitions.
=> Fix #9: running `import_files` from any subdirectory of Alpenhorn root

alpenhorn/update.py
- Turn on `--sparse` (= `-S`) mode in rsync
- Use long names of rsync options, rather than flags
(Merged into v1 master as 72d4543)
=> Port PR#5 from V1: Efficient handling of sparse files in Rsync

alpenhorn/client/acq.py, tests/test_client_acq.py
Example output:
```
$ alpenhorn acq where ACQ
Storage node: x
Name      Size  Has    Wants
------  ------  -----  -------
fred       512  N      Y
sheila     512  X      M
Storage node: z
Name      Size  Has    Wants
------  ------  -----  -------
fred       123  Y      Y
```
Help text:
```
$ alpenhorn acq where --help
Usage: cli acq where [OPTIONS] ACQUISITION
List locations of files that are in the ACQUISITION.
Options:
-h, --help  Show this message and exit.
```
=> feat(cli): Add `acq where` subcommand to show location of archive copies

alpenhorn/io/ioutil.py, alpenhorn/pool.py, tests/io/test_ioutil.py, tests/test_pool.py
BBCP needs different ports in each worker to allow multiple instances to run simultaneously.
It will use port `4200 + 10N` in worker number N.  This mirrors what I was doing in the non-alpenhorn gong transfer shell scripts that I was running.
I have already deployed this to cedar.
=> fix(ioutil): Dynamic BBCP ports

alpenhorn/update.py, tests/test_update_group.py
If there are multiple pending requests for the same file to the same group, alpenhorn should only ever be willing to process one of them.
We take the first one we see, and ignore the rest.  (They'll get dealt with later, once the one we're working on has been resolved.)
=> fix(update): Handle duplicate requests

alpenhorn/client/cli.py, alpenhorn/common/util.py, alpenhorn/server/service.py
=> feat(cli): --version option for server and client

pyproject.toml
There's a lot of subpackages now.  And there will be more coming with the client re-write.
=> fix(pyproject): Find subpackages

alpenhorn/io/_default_asyncs.py
The `IntegrityError` can help us instead of being a problem:
Naively try to create a new record and if that fails because one already exists, _then_ try to update the existing record.
Closes #213
=> fix(io._default_asyncs): Handle pre-existing AFCR

alpenhorn/common/util.py
Dah.  I do this all the time...
=> fix(util): Fix f-string

alpenhorn/cli/acq/__init__.py, alpenhorn/cli/acq/create.py, tests/cli/acq/test_create.py
There's not much to an ArchiveAcq, so there's not much to this command.
=> feat(CLI): "acq create" command

alpenhorn/cli/group/show.py, alpenhorn/cli/node/show.py, tests/cli/group/test_show.py, tests/cli/node/test_show.py
Summarises pending transfers into GROUP / out from NODE.
In both cases, also present in the `--all` output.
=> feat(CLI): group/node show --transfers

alpenhorn/cli/file/__init__.py, alpenhorn/cli/file/import_.py, alpenhorn/cli/group/autosync.py, alpenhorn/cli/group/show.py, alpenhorn/cli/group/sync.py, alpenhorn/cli/node/activate.py, alpenhorn/cli/node/autoclean.py, alpenhorn/cli/node/clean.py, alpenhorn/cli/node/create.py, alpenhorn/cli/node/deactivate.py, alpenhorn/cli/node/init.py, alpenhorn/cli/node/list.py, alpenhorn/cli/node/modify.py, alpenhorn/cli/node/scan.py, alpenhorn/cli/node/show.py, alpenhorn/cli/node/stats.py, alpenhorn/cli/node/verify.py, alpenhorn/cli/options.py, tests/cli/file/test_import.py
This is another very simple one: it just creates a new ArchiveFileImportRequest and leaves the daemon to do the hard work.
Has been rebased onto #250
=> feat(CLI): "file import" command

alpenhorn/common/util.py, alpenhorn/io/_default_asyncs.py, alpenhorn/io/ioutil.py, tests/io/test_defaultnode_pull.py, tests/io/test_ioutil.py
If there's no other way to copy a local file, use shutil.copy to do it.  The implementation here is very similar to hardlinking, which will be attempted first.  Alpenhorn will do a md5sum of the copied file after the copy completes to verify it was copied correctly.
I've made a new function `common.util.timeout_call` to provide an asyncio wrapper for I/O calls which need to be cancellable.
Also fixed a few tests that were using the `tmp_path` fixture instead of the extended PyFakefs fixture which I've developed (`xfs`).  I don't why they were like this, but probably they were early tests written before full development of `xfs`.
Closes #241
=> feat(io): shutil.copy fallback

alpenhorn/daemon/auto_import.py
A few fixs for the auto-import code after running it through its paces in the docker demo.
Fix race condtion in `_import_file`
-----------------------------------
In `_import_file`, we now use a full get-create-get idiom to avoid race conditions, i.e.:
* try to get an existing record
* if that fails because the record doesn't exist, try to create the record
* if that fails because the record (now) exists, then get the existing record
Previously the second get wasn't there, but that can cause problems if another thread/process creates the record between steps one and two.  This is how `peewee`'s own `get_or_create` helper function works, but we can't use that here because the `register` flag means we sometimes stop the attempt if step one fails.
More filtering in the `RegisterFile` handler …
=> fix(auto_import): Improvements found via the demo

alpenhorn/cli/node/show.py, tests/cli/node/test_show.py
This adds a flag, `--imports` to `node show` to request a list of pending `ArchiveFileImportRequest`s (like `--transfers` does for transfer requests).
Includes special handling for node init requests (which are handled via the `ArchiveFileImportRequest` table).
=> feat(cli): Add `--imports` to `node show`

alpenhorn/db/storage.py
This replaces the previous implementation, which ended up performing one query per file present on the node, with a faster one which invovles only a single query.
The old implementation worked fine in the test suite where there might be, say, five files, but took tens of minutes on gong, where there are ~10,000 files.  This new implementation takes seconds on gong.
=> perf(db): Re-implement StorageNode.get_all_files

LICENSE, pyproject.toml
Trying to get this ready for PyPI
=> build: Fixes for packaging

examples/pattern_importer.py
Noticed by Josh during the demo.
=> fix(pattern_importer): Fix return type for check_match

doc/demo.rst
Add a section on auto-actions to the demo.  Plus some mild copy-editing.
Read here: https://alpenhorn.readthedocs.io/en/doctest/demo.html#auto-actions
=> docs(demo): Add auto-actions to demo
