radiocosmology/alpenhorn

- alpenhorn/acquisition.py
- alpenhorn/auto_import.py
- tests/fixtures/files.yml
- tests/test_import.py
* Importing a file asks each of the registered acquisition types if the dirname belongs to it. If none can handle it, the rightmost segment of the directory is removed and the process started again.
* First match wins, and the rest of the path to the file becomes the file name.
* The file name is tried on each of the acquisition's file types, and in case of no matches the file is skipped -- we don't try to repeat the loop on the subset of the file name's path segments as we do with acquisitions.
* The `auto_import.import_file` now has one fewer argument, since has to decide where the file's path gets broken into the acquisition vs the file name.
**Please note:** a number of TODOs are my questions over some implementation details. Let me know what you think.
> Allow nested acquisition directory and file structure (fixes #4)

- alpenhorn/config.py
- test-requirements.txt
- tests/test_config.py
I've added support for loading configuration files. The paths it checks are basically the ones recommended in the XDG standards, but that means they are a little linux specific (especially the /etc/xdg/ one). But I think that's alright.
> Configuration loading support

- .travis.yml
- alpenhorn/__init__.py
- alpenhorn/auto_import.py
- alpenhorn/client.py
- alpenhorn/config.py
- alpenhorn/db.py
- alpenhorn/extensions.py
- alpenhorn/generic.py
- alpenhorn/service.py
- alpenhorn/storage.py
- setup.py
- tests/test_acquisition_model.py
- tests/test_archive_model.py
- tests/test_extensions.py
- tests/test_storage_model.py
This is a moderately large set of changes that implement support for
loading extensions into alpenhorn from the given configuration, and
has the first steps to getting `alpenhornd` running.
In addition to the headline changes it has a number of smaller additions:
- A new, working, implementation of ENUM for all database types.
- Removed SqliteEnum hacks from tests as Sqlite should be supported
natively now.
- Rewrote database connection code to work with the config.
- Added an `init` command to `alpenhorn` for creating the required tables.
- Added Python versions back to Travis testing.
- Added script entry points back into `setup.py`
- Removed some exception classes mistakenly brought in from the layout db.
- Added a custom database connection class that is a hybrid of Proxy and …
> Alpenhorn service and extension support

- tests/docker/Dockerfile.alpenhorn
- tests/docker/Dockerfile.base
- tests/docker/alpenhorn.conf
- tests/docker/custom_test_types.py
- tests/docker/test_docker.py
This pull requests adds in the ability to test the behaviour of alpenhorn running across multiple systems. It uses docker to setup a test system of several instances of alpenhornd running against a separate MySQL system.
These tests are pretty lightweight for what they are, but compared to the unit tests they will take a lot more time.
To run the tests, simply install Docker (this was easy enough on my laptop using Docker for Mac), install the docker python SDK `pip install docker`, and set the environment variable `RUN_DOCKER_TESTS`.
> Functional tests using Docker

- alpenhorn/acquisition.py
- alpenhorn/archive.py
- alpenhorn/auto_import.py
- alpenhorn/client.py
- alpenhorn/config.py
- alpenhorn/db.py
- alpenhorn/extensions.py
- alpenhorn/logger.py
- alpenhorn/service.py
- alpenhorn/storage.py
- alpenhorn/update.py
- alpenhorn/util.py
- tests/test_acquisition_model.py
- tests/test_archive_model.py
- tests/test_client.py
- tests/test_extensions.py
- tests/test_import.py
This pull request is a cleanup of the logging code, switching to getting a logger object at the module level direct from `logging`, and having `alpenhorn.logger` be only for configuring the logging output.
Most recommendations for python are to simply allow logging output to go to stdout and then let the system process it with its own tools (systemd, syslog etc). This is mostly fine, and is what should do by default, but on machines where alpenhorn doesn't run as a proper service (e.g. SciNet for CHIME), then we might need to specifically configure file locations. That ability has been removed in this PR, and so should be brought back later.
> Tidied up the logging code

- requirements.txt
We have incompatibilities with API changes introduced in PeeWee v3, so until
this is resolved, we should require v2.7 and up to but excluding v3.
> Require PeeWee v2 (#27)

- test-requirements.txt
- tests/docker/test_docker.py
Since v3, `Container.exec_run` returns a tuple of (exit_code, output)`.
We could also check `docker.__version__` after importing, and raise an exception if it's not `=~ 3.0`.
> #28: use docker-py v3 API

- alpenhorn/acquisition.py
This was presumably copied from the original alpenhorn.
> Doc update: rm non-existent column.

- tests/test_acquisition_model.py
- tests/test_archive_model.py
- tests/test_client.py
- tests/test_import.py
- tests/test_storage_model.py
Pytest deprecated direct calling of fixtures in release 4. Instead, the
[recommended pattern][1] is to refactor the "callable" part of the fixture into a
regular function, and call that from any fixture that needs it.
[1]: https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly
> Refactor test fixtures to work in Pytest v4

- setup.cfg
Using Pyfakefs in fixtures triggers, perhaps indirectly, the import of the
'compiler' package. That, in turn, prints out a deprecation warning because it
is removed in Python 3. This kind of warning is by default filtered out by the
Python interpreter; however, Pytest v3.8 introduced displaying deprecation
warnings [[1]], so that this annoying message now shows up in every test run that
includes tests/test_config.py.
Luckily, Pytest also provides a mechanism to filter out specific warnings, so
that ignoring the warnings about importing 'compiler' can be added to setup.cfg.
[1]: https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
> Configure pytest to ignore deprecation warning for compiler package

- alpenhorn/acquisition.py
Since we allow nested directories inside acquisitions, file names can easily get
longer than the current 64-character limit. Raising this to 255 is at least in
line with filename limit on common Linux filesystems, although even that is not
quite enough for any possibility, as the maximum *path* length in current Linux
is usually 4,096 bytes.
> Increase the limit for file name to 255 characters

- alpenhorn/acquisition.py
The calling code invokes `AcqInfo.set_info()` with both `acqpath` and
`node_root`, but the abstract method in AcqInfoBase is missing the 'node_root'.
> Add missing method argument `node_root` to AcqInfoBase.set_info

- alpenhorn/service.py
Commit 9ce8954d34136a2bf7641b6e8a7c37f5c91ae7cd neglected to import
`alpenhorn.util` in `alpenhorn.service`. This adds it.
> Add missing `util` import (#71)

- alpenhorn/db.py
- tests/test_db.py
RobustProxy doesn't work as intended, because to really override `Database.execute_sql` it has to be used as a mixin for the Database object, not a subclass of peewee.Proxy.
This commit restores the old `RetryOperationalError`, updated for the current Peewee APIs, and dynamically adds its type to the result of db_url.connect(). `db.database_proxy` goes back to being an instance of `peewee.Proxy`.
> Restore RetryOperationalError mixing (fix #76)

- alpenhorn/client.py
- tests/test_client.py
We detected the error case, but were missing the early exit statement, so the
processing continued assuming the variable was properly initialized.
> Fix #34: Fix UnboundLocalError when `mount`-ing a non-existent node

- alpenhorn/client.py
- tests/test_client.py
We can use click.Choice to get a more descriptive error message for the user,
and proper error exit.
> Better handling of illegal value of `--storage_type` in `create_node` (fixes #46)

- alpenhorn/client.py
- tests/test_client.py
It's not really an error if the node is already mounted, as it means that
Alpenhorn can just proceed to activating it.
> Fix #61: allow already mounted node filesystem in `mount_transport`

- alpenhorn/client.py
- alpenhorn/update.py
- alpenhorn/util.py
- tests/test_client.py
This was already used in the Alpenhorn service to detect the case when a remote
mount went away. We now do the same check in the client command, so that it
prevents mistakenly mounting a storage node under another node's mountpoint.
> Add a check for ALPENHORN_NODE file when mounting the node (fix #7)

- alpenhorn/client.py
- tests/test_client.py
This has long been a source of confusion to the users, as a newly created node
would not appear in the output of `status --all`, making it look like something
went wrong with node creation.
> Include nodes that have no files in `status` output (closes #38)

- tests/test_update.py
This would have caught the runtime error fixed in the previous commit, without
having to run the full Docker tests, which don't get run during CI.
> Create unit tests for steps in the update loop

- alpenhorn/client.py
- tests/test_client.py
Instead of raising an exception with a pile of traceback, it's friendlier to the
user and conveys just as much detail to print out an error message and exit with
status code 1.
> Show a better error message on bad arguments in `sync` (fix #47)

- alpenhorn/client.py
- tests/test_client.py
- improves the help text and progress messages to make it clearer what's being cleaned means
- have a way to undo a "clean" request
- signal user errors with non-zero exit code
> Improve user-friendliness of the `clean` command

- alpenhorn/archive.py
- alpenhorn/client.py
- alpenhorn/update.py
- tests/fixtures/archive.yml
- tests/test_client.py
- tests/test_update.py
This implements schema changes proposed in #57 and #63, namely:
Instead having ArchiveFileCopyRequest have a single instance for each `(file, node_from, group_to)` combination, and updating them in place as a new copy operation is requested after being completed or cancelled once, this changetracks the copying at a request level by:
1. adding new columns for start and end time of the transfer
2. once a copy request is completed or cancelled, requesting the copying of a file again will create a new instance of a copy request for the same `(file, node_from, group_to)`.
With this semantics of copy requests, the `n_requests` column becomes redundant and is removed.
> Finer-grained ArchiveFileCopyRequest tracking and accounting

- alpenhorn/archive.py
- alpenhorn/auto_import.py
- alpenhorn/client.py
- alpenhorn/update.py
- tests/test_archive_model.py
- tests/test_update.py
This reflects the "true" size of the file, as used by the filesystem. (E.g.,
accounting for holes in sparse files or Lustre filesystem compression.)
> Add true size field to ArchiveFileCopy (closes #58)

- alpenhorn/update.py
With the check at the bottom of the loop, there were cases where a `continue` on
persistent rsync errors causes the loop to keep running forever, since it never
gets to the timeout check.
> Fix #101: check for update timeout at the top of the processing loop

- alpenhorn/client.py
- tests/test_client.py
This allows us to import files on a field node without having to run the daemon, or if we want to be selective about which directories to import.
> Add an option for client 'import_files' to perform auto-import

- alpenhorn/client.py
- tests/docker/test_docker.py
ArchiveFile.size_b is defined as peewee.BigIntegerField, which at least in
latest Peewee and Python 2.7 is returned as a `decimal.Decimal` value, so
calculations with floats can't be done without an explicit cast.
> Fix #109: `alpenhorn status` failing with MySQL backend

- alpenhorn/util.py
- tests/test_client.py
Otherwise, running `alpenhorn activate` will fail because `alpenhorn_node_check`
failed if the node was not active. (A catch-22.)
This does mean that the callers of `alpenhorn_node_check` need to ensure the
StorageNode.active is in the correct state, but they currently all do.
> Fix #113: Only check ALPENHORN_NODE in `util.alpenhorn_node_check`

- alpenhorn/client.py
- tests/test_client.py
Using parted seems to trigger a reload of udev rules and so the device file goes missing briefly after it returns. This means that a) we should only use parted if we really have to; and b) include a short sleep after it to let udev to recreate the device files so the next process (e2label or mkfs) can find it.
Also, it's now recommended to use functions in module `subprocess` to run subprocesses instead of `os.system` and `os.popen`/`popen3`.
> Revise mechanics in `client.format_transport`

- alpenhorn/client.py
- tests/test_client.py
`util.alpenhorn_node_check`'s argument is a `StorageNode`, not its name as
`client.verify` was passing. Also, it's now up to the caller to check that the
node is active, which was missing in `verify`.
Finally, the test for the `verify` method mocked `alpenhorn_node_check`, so this
bug was masked in testing. I removed the mock and now test all code paths
realistically.
> Fix #118: `verify` called `alpenhorn_node_check` with wrong argument

- alpenhorn/client/node.py
- tests/test_client_node.py
When an `--acq` option is specified in the `node verify` command, we can
dramatically reduce the initialy database query by including a `WHERE IN`
clause. Currently, the `--acq` filter is handled after the query, while
iterating through the query's resultset.
> More efficient database querying when verifying only a subset of acqs

- tests/test_client_node.py
To keep regex escape sequences (e.g., `\s`) from accidentally being interpreted
as regular Python string escapes, it's safest to just always specify regular
expressions with raw strings.
> Always use raw strings to capture regular expressions

- tests/test_client_node.py
This definitely did not use to fail, and it check an error message thrown by Click itself, so it might be a recent update switched between single and double quotes to show valid choices for a multi-choice parameter.
> Fix a failing unit test caused by checking for wrong quotes

- alpenhorn/client/__init__.py
- alpenhorn/client/acq.py
- tests/test_client_acq.py
Current commands:
- `list [NODE]`: with NODE given, lists names of acquisitions and a count of
their files for data present on the node. Without the argument, lists all
known acquisitions. (Can be long!)
- `files ACQ`: lists the names of all files that are a part of the acquisition.
> Add a 'acq' subcommand to the CLI for listing details of acquisitions

- alpenhorn/queue.py
- test-requirements.txt
- tests/conftest.py
- tests/test_db.py
- tests/test_queue.py
This PR introduces a "Fair Multi-FIFO Queue", which will be used by alpenhorn as the task scheduler.  (It doesn't use it yet, as the code introduced here isn't actually used anywhere yet.
The FMFQ is a multi-producer, multi-consumer queue designed to be similar to the standard `queue.Queue` though it doesn't derive from that code, nor is it a drop-in replacement for it.  All items in the queue are assigned to a FIFO (of which there are many).  The FIFO for a given item is specified by a key.  The queue is "fair" in the sense that it tries to keep the same number of items in-progress at any given time.  (Same number _in-progress_ not _queued_.)
The FIFOs are implemented as `deque`s, though I don't know if that really saves us a whole lot of time.
The queue is unbounded.
Like the standard …
> Rewrite 2/10: The Fair Multi-FIFO Queue

- alpenhorn/logger.py
- alpenhorn/pool.py
- alpenhorn/task.py
- tests/test_pool.py
- tests/test_task.py
This PR adds the asynchronous Task (a callable object containing the code of an I/O job), the Worker (a thread object that executes Tasks), and the Pool (a container which manages the Workers).  This PR does not integrate these new objects with the rest of alpenhorn (for that, see #148), but does make use of the queue introduced in #145.
The `Task` class is a callable container class.  I/O tasks are made by creating instances of this class by providing the Task class with a function (containing the I/O code) along with any arguments needed to be passed to the function.  The first positional argument to a task function will be the task object itself.
Tasks are immediately and automatically placed onto the queue when they are instantiated, which might seem a little unintuitive, and …
> Rewrite 3/10: Tasks and Worker Pool

- alpenhorn/config.py
- alpenhorn/db.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/service.py
- alpenhorn/storage.py
- alpenhorn/update.py
- alpenhorn/util.py
- tests/conftest.py
- tests/test_service.py
- tests/test_storage.py
- tests/test_update.py
- tests/test_update_group.py
- tests/test_update_node.py
- tests/test_util.py
This PR introduces the I/O framework for `StorageNode`s and `StorageGroup`s, although none of the actual I/O is implemented in this PR.  It also rewrites the daemon main loop to integrate the queue, workers, and new I/O framework, although, again, the existing I/O is left as-is for now and does not make use of the new asynchronous task structure.
This PR adds two new optional (i.e. null-allowing) string fields to both `StorageGroup` and `StorageNode`:
* `io_class` which provides the name of the I/O class for a node/group.  Node and group I/O classes are separate, and a the list of valid names is different for each.  If this field is left empty, it is treated as if it had the value `Default`.
* `io_config` which provides a JSON blob of configuration data, if any, to be interpreted by the …
> Rewrite 5/14: I/O framework

- alpenhorn/extensions.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/storage.py
- alpenhorn/update.py
- alpenhorn/util.py
- tests/conftest.py
- tests/io/test_defaultnode.py
- tests/io/test_defaultnode_check.py
- tests/test_extensions.py
- tests/test_service.py
- tests/test_storage.py
- tests/test_update_node.py
- tests/test_util.py
_This is the first of four PRs to move I/O operations to the `DefaultIO` framework._
Three parts of the update loop are handled here:
* node check (checking for the `ALPENHORN_NODE` file).
* free space update
* integrity check of file copies with `has_file=='M'`
Also, I've made a change to the way third-party I/O classes are loaded; see the following section.
Following discussion with Richard, this PR modifies how third-party I/O modules are found by alpenhorn from the behaviour originally introduced in Rewrite part 5/14 (#148).
The old behaviour was to simply have the full import path given in, say, `StorageNode.io_class`.  Instead of doing that, this PR introduces a new extension type called "io-module" which extensions should use to provide alpenhorn with third-party I/O modules.   The …
> Rewrite 7/14: DefaultIO housekeeping + integrity check

- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/update.py
- tests/io/test_defaultnode_delete.py
- tests/test_service.py
- tests/test_update_node.py
This is a relatively straightforward PR which mostly moves the guts of `update.update_node_delete` into `alpenhorn.io._default_asyncs.delete_async` which gets shoved into a task by `node.io.delete`.
I can't tell if it is for sure, but it seems weird to make an asynchronous task to delete a single file, so I've made the remaining code in `update.update_node_delete` group a bunch of them together and pass that to the I/O layer to delete together in the same task.
The bunch size I've chosen is 10.  Don't really know if that's a good number.  It's in the ballpark of the number of files that alpenhorn-1 tends to delete at a time (which, in turn, is related to the number of files it can transfer per hour).
I'm willing to entertain different values for the bunch size, including the value 1 (i.e. …
> Rewrite 8/14: DefaultIO file deletion

- alpenhorn/archive.py
- alpenhorn/config.py
- alpenhorn/db.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
- alpenhorn/update.py
- alpenhorn/util.py
- tests/conftest.py
- tests/io/test_ioutil.py
- tests/io/test_ioutil_crd.py
- tests/test_util.py
This PR primarily moves parts of the file transfer code out of `update.py` and into `alpenhorn/io/ioutil.py`.  My original thought with these bits was that they would be useful to other I/O types other than the `Default` I/O, but that hasn't actually happened in this rewrite.  Nevertheless, it's good to split up the unmanageably long `update_node_requests`.
This PR removes my ham-fisted attempt to create an auto-updating `CurrentTimestampField` (using MySQL's `ON UPDATE CURRENT_TIMESTAMP` clause) from way back in part 4 (#147) which wasn't going to work for a number of reasons.  In it's place is a simple `DateTimeField` which gets explicitly updated when necessary.
The only potential downside here is that changes made to the `ArchiveFileCopy` table outside of alpenhorn won't benefit from …
> Rewrite 9/14: I/O util (pull request inner functions)

- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/updownlock.py
- alpenhorn/update.py
- tests/conftest.py
- tests/io/test_defaultgroup.py
- tests/io/test_defaultnode.py
- tests/io/test_defaultnode_delete.py
- tests/io/test_defaultnode_pull.py
- tests/io/test_defaultnoderemote.py
- tests/io/test_updownlock.py
- tests/test_service.py
- tests/test_update_group.py
- tests/test_update_node.py
This PR completes the re-write of `update.py` to transition to the new I/O framework by re-implementing support for pull requests.
This is a fairly simple thread synchronization primitive that I'm a little surprised it doesn't already exist.
It's used to prevent race conditions during the modifications of a node directory tree by only allowing either creation or deletion to happen at any given time.  It's needed to prevent the following (starting from a node with only one file on it, `/node/acq/file1`:
```
worker1 (pulling)                       worker2 (deleting)
-----------------------                 -----------------------
wants to create:                        wants to delete:
/node/acq/file2                        /node/acq/file1
----------------------- …
```
> Rewrite 10/14: DefaultIO file pulls

- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/transport.py
- alpenhorn/update.py
- tests/io/test_defaultnode.py
- tests/io/test_transport.py
- tests/test_service.py
- tests/test_update.py
This PR adds a new group I/O class, `TransportGroupIO` suitable for use with a transport group to fix the removal of transport group logic from `update.py` in the previous PR.
Features of a Transport StorageGroup:
* it may have any number of nodes.  All node must have `node.storage_type == 'T'`, but no restrictions are put on the I/O class of nodes.  Nodes in the group which have a different `storage_type` are ignored.
* all pulls to the StorageGroup must be local: non-local pull requests will be ignored
* when handling pull requests, transport nodes are prioritised by increasing free space: the group will attempt to pull a file to the fullest node that it thinks it will fit on.
The name of the group is no longer special (previously, the group had to be named "transport") and more than …
> Rewrite 11/14: Transport Group I/O

- alpenhorn/auto_import.py
- alpenhorn/io/lfs.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/lustrequota.py
- tests/conftest.py
- tests/io/test_lfs.py
- tests/io/test_lustrehsmgroup.py
- tests/io/test_lustrehsmnode.py
- tests/io/test_lustrequota.py
- tests/test_auto_import.py
- tests/test_service.py
- tests/test_update.py
This PR add the Lustre I/O classes.
I've made a wrapper around calls to the `lfs(1)` binary in `alpenhorn.io.lfs.py`.  It is not a complete wrapper for that command and only able to run these commands:
* "lfs quota" to retrieve the group quota for a path.  The user group used must be specified in the I/O config.  Can also handle the quota max override needed for cedar's `/nearline`.
* "lfs hsm_state" to retrieve the HSM state for a file.  The state itself is represented with the `HSMState` enum and is one of:
* `MISSING`: file is not present on disk or tape
* `UNARCHIVED`: file exists on disk, but not on tape
* `RESTORED`: file exists on both disk and tape
* `RELEASED`: file exists on tape only
* "lfs hsm_restore" changes state `RELEASED -> RESTORED`
* "lfs hsm_release" changes state …
> Rewrite 13/14: Lustre I/O

- alpenhorn/acquisition.py
- alpenhorn/archive.py
- alpenhorn/auto_import.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/storage.py
- tests/io/test_ioutil_crd.py
- tests/test_acquisition.py
- tests/test_archive.py
- tests/test_auto_import.py
- tests/test_storage.py
- tests/test_update_node.py
The `datetime`s are all naive because peewee doesn't work well with TZ-aware ones.
Closes #159
> fix: Store/read (naive) UTC datetimes to/from DB.

- requirements.txt
- test-requirements.txt
Might be better just to drop the requirement, which would require rewriting examples/pattern_imorter.py
Closes #160
> fix(setup): Move globre requirement to test-requirements

- alpenhorn/config.py
- alpenhorn/logger.py
- alpenhorn/service.py
- requirements.txt
- tests/conftest.py
- tests/test_logger.py
Allows optional configuration to start up file or syslog logging.  File logging may include file rotation and/or watching.
Rotating file logging is necessary for running on cedar.  Log messages emitted before enabling the log file are buffered and flushed to the log file once it is opened, meaning the config-loading code can still use the log even before a log-file is opened.
Moves the initial logging setup from import time to an explicit call to `init_logging`.
Closes #161
> feat(logger): configure syslog and file logging

- alpenhorn/db.py
- alpenhorn/pool.py
- alpenhorn/service.py
- tests/conftest.py
- tests/test_db.py
- tests/test_service.py
peewee already handles threadsafety of the inherently not threadsafe MySQL connection, so there's no need for us to second guess it.
This changes the way the DB framework is initialised: all initialisation happens in the main thread.  peewee is smart enough to open per-thread connections to the database on demand in the worker threadds.
As a result, the default DB code (which CHIME doesn't use) is now reported to be threadsafe, which is nice.
> fix(db): Don't initialise peewee DB in every thread

- alpenhorn/config.py
- alpenhorn/db.py
- alpenhorn/io/base.py
- alpenhorn/io/ioutil.py
- alpenhorn/io/lfs.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/logger.py
- alpenhorn/pool.py
- alpenhorn/storage.py
- alpenhorn/update.py
- requirements.txt
- tests/conftest.py
- tests/io/test_defaultnode_pull.py
- tests/io/test_ioutil.py
- tests/io/test_lfs.py
- tests/test_update_group.py
I don't think these are big enough to merit their own PRs:
Also:
* renamed BaseNodeIO.update() to BaserNodeIO.set_storage().
* enforce keyword arguments in UpdateableGroup.reinit().
The "set_storage" methods are called at the top of every update loop to replace the StorageNode/Group of the I/O classes. "update" was a very poor choice for their name because there are already too many things referred to as "update", and the name was always just going to lead to confusion.
(The erstwhile "update()" method was always called _before_ the "before_update()" method, which is a pretty clear indication there's something wrong with the name.)
Ported from https://github.com/chime-experiment/chimedb/pull/40
`run_command` only accepts strings.
I get the idea of using `{"level": "warning", …
> Various small fixes found during the cedar shakedown

- alpenhorn/io/lustrehsm.py
- alpenhorn/update.py
- tests/io/test_lustrehsmnode.py
- tests/test_update_group.py
I think these were overlooked because of my initial idea of making `ArchiveFileCopy.last_update` an automatically-updating value, which didn't pan out.
> fix: Update ArchiveFileCopy.last_update as needed

- alpenhorn/auto_import.py
- alpenhorn/io/ioutil.py
- alpenhorn/storage.py
- alpenhorn/update.py
- tests/conftest.py
- tests/io/test_defaultnode_pull.py
- tests/io/test_ioutil.py
- tests/io/test_ioutil_crd.py
- tests/test_service.py
- tests/test_storage.py
- tests/test_update_node.py
This PR handles a few potential race conditions in the way CHIME moves data around its Storage graph.  There are two parts.
The easier part is a change to the way alpenhorn collects files for deletion.  It now skips deleting a file copy which is needed to fulfill a copy request.  It doesn't cancel the deletion, so it will consider deleting it again next time, but deletion won't actually occur until the blocking copy request is handled (completed or cancelled), avoiding a potential race condition in file management.
The bigger change here is the addition of a table providing metadata for the edges in the Storage directed graph (edges in a directed graph are usually called "arrows").   This is the table `StorageTransfer` defined in `storage.py`.
We've talked about edge tables for a long …
> feat: Edge table and transfer race condition fixes

- alpenhorn/update.py
- tests/test_update_node.py
Instead, they'll just be skipped by the running process, which has the same effect as an inactive node, except that alpenhornd will re-check the node each time through the main loop.
This should mean alpenhorn can recover from intermittant I/O issues on /project space at cedar.
> fix(update): Don't deactive nodes with I/O issues

- alpenhorn/auto_import.py
- alpenhorn/client/__init__.py
- alpenhorn/db.py
- alpenhorn/extensions.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/ioutil.py
- alpenhorn/io/lfs.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/lustrequota.py
- alpenhorn/io/polling.py
- alpenhorn/io/transport.py
- alpenhorn/storage.py
- alpenhorn/update.py
- alpenhorn/util.py
- examples/pattern_importer.py
- tests/conftest.py
- tests/io/test_defaultnode.py
- tests/io/test_defaultnode_check.py
- tests/io/test_lustrehsmnode.py
- tests/io/test_transport.py
- tests/test_extensions.py
- tests/test_logger.py
- tests/test_update_group.py
- tests/test_util.py
A `PermissionError` while checking a file will now result in it being considered corrupt.
_Bonus_: fixed some ham-fisted mocking in `tests/io/test_lustrehsmnode.py` which was not being properly cleaned up after the test finished.
Closes #176
> fix(io.default): Handle PermissionError during check

- alpenhorn/util.py
Normally, when a transfer times out, it's because it's stuck deep down in I/O wait, meaning SIGKILL
is not going to be handled in a timely manner, and, so, trying to `.communicate()` with it again is just futile.
With the current code, after a timeout, the worker just gets stuck in the same wait it tried to get out of with the kill, as if there were no timeout given.
So, let's just send it a kill and then abandon it.
Related to #175 (abandonning subprocesses may lead to zombies), but this doesn't really address the items brought up in that issue, which are higher-level ideas.
I have deployed this to cedar.
> fix(run_command): fix subprocess timeout recovery

- alpenhorn/update.py
- tests/test_update_group.py
- tests/test_update_node.py
These files will just be ignored (i.e. no attempt to make them ready).
Also: cancel AFCRs for files which don't exist on the source.
> fix(update): Don't ready missing files for pull

- alpenhorn/io/_default_asyncs.py
Multiple threads can try to create the same directory, which created a race condition between checking for the existance of a directory and actually trying to make it
> fix(_default_asyncs): fix race condition when making new directories

- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/ioutil.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/update.py
- tests/io/test_defaultnode.py
- tests/io/test_ioutil.py
- tests/io/test_lustrehsmnode.py
- tests/test_update_node.py
This adds an attempt to clean up a DefaultIONode during an idle update by:
* looking for `.placeholder` files and deleting them
* attempting to remove acq directories
Because this routine runs when the node is idle (i.e. only when there's no other I/O occurring), no placeholders should be on the node.  Any which are found are clearly spurious due to prior crashes.
I've also implemented a check to reduce how often it runs. It will always run at start-up (when I suspect most uncleanliness would be found), and then once every 100 times the node transitions from not-idle to idle.  Not really sure how often is appropriate.  It might even be sufficient to only run it on start-up.
While implementing this, I discovered that the code that was deleting acq dirs wasn't stopping at the …
> feat(io/default): Try to clean up during idle updates

- examples/pattern_importer.py
- test-requirements.txt
- tests/test_service.py
Back in #163 I was content to solve #160 by demoting `globre` from a requirement to a test requirement, but I think even here it's an unnecessary complication for something we're not using in production.
This rewrites the `pattern_importer` example extension to accept only regular expressions and updates the patterns in `tests/test_service.py` to follow.
Also updated how the `pattern_importer` is imported in the `test_service` test to handle cases where the current directory is not in the import path or the test suite isn't run from the top-level alpenhorn directory.
Closes #131
> Drop globre from test requirements

- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/update.py
- tests/io/test_lustrehsmnode.py
- tests/test_update_node.py
This changes the way "auto-verify" works: instead of separate "auto_verify" I/O methods, the auto verify code now just marks files for check (`has_file='M'`), and then the regular check mechanics can do the actual checking.  This greatly simplifies things.
The `check` method on nearline now handles release/restore as needed and the `exists()` check has been moved into the async.
This is a partial fix for #183.
> fix(update): Merge auto-verify into check

- alpenhorn/io/lustrehsm.py
- tests/io/test_lustrehsmnode.py
This is the second part of the fix for #183 which fixes how the `ready_pull` function works.  All I/O for `ready_pull` is now in a task and out of the main thread.
In the previous PR I added some slap-dash "race condition insurance" which I've removed here and replaced with a more robust system to restore-and-wait for a file which provides a way to track files already being waited on for restore.  (Which was otherwise impossible to do because yielded tasks are essentially hidden from the system while they're deferred.)
Now `check`s and `ready_pull`s won't be re-queued if they're already waiting for a file to be restored.
Closes #183
> fix(LustreHSM): Move ready_pull I/O out of main thread

- alpenhorn/io/ioutil.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/pool.py
Calling it more than once seems to result in the second call not completing until the file is restored (locking up the worker).
Probably we should add a timeout to the restore-wait (#188) but I want to run it as-is for a while to see how this goes.
Also, fixed the `check_async` call.
Also, some logging tweaks.
> fix(lustrehsm): Only call hsm_restore once during restore-wait

- alpenhorn/auto_import.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/transport.py
- alpenhorn/update.py
- tests/conftest.py
- tests/io/test_defaultgroup.py
- tests/io/test_lustrehsmgroup.py
- tests/io/test_transport.py
- tests/test_update.py
- tests/test_update_group.py
- tests/test_update_node.py
This fixes another instance of unnecessary I/O in the MainThread.  Specifically, when processing a pull request, the UpdateableGroup was searching the group's node(s) for a hitherto unknown copy of the file on disk (which can happen if alpenhorn crashes during a pull).
This check has been moved to a Task (`_default_asyncs.group_search_async`) and is now done later in the pull request processing, after non-I/O checks have finished (which should, overall, reduce the amount of I/O going on).
The `group.io.pull` method has been broken into two pieces:
* `pull_force` which does what the prior `pull` method did: chooses a node to receive the file and dispatch the request to that node, and
* a new `pull` which runs the search asyncm which, in turn, will call `pull_force` to pull the file, if the …
> fix(update): Remove I/O from main loop pull handling

- alpenhorn/config.py
- alpenhorn/io/base.py
- alpenhorn/io/ioutil.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/update.py
- tests/conftest.py
- tests/io/test_defaultnode.py
- tests/test_logger.py
- tests/test_update_group.py
I don't want to add a ruff check to the CI yet, because the alpenhorn client code is very broken, but here are some fixes found by running it manually.
Most of these are unused variables.  In peewee `.where` clauses, `<field> == True` can't be converted to `is True` because (as explained in the peewee docs) `is` can't be overloaded like `==` can.   So in those cases, I've disabled the specific check (`# noqa: E712`).
> fix errors found by ruff

- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
Yesterday's failure goes like this:
* alpenhorn start
* "tidy up" task from #182 starts because node is idle
* pull request task starts during group update
* pull task creates new directory and placeholder file
* tidy-up task deletes placeholder file and new directory
* bbcp creates file as directory name (because that's the "target" it was given).
This PR doesn't actually fix this problem. (I'm working on another PR for that), but this does provide some mitigation so that, if a third-party comes by and deletes a destination directory during a pull, the pull will fail (due to missing target directory), instead of wrongly creating the destination file as the target directory name.
Also renamed the parameters in `ioutil.bbcp` and `ioutil.rsync` to something more generic to indicate they're …
> fix(_default_asyncs): Use full path for copy target

- alpenhorn/queue.py
- alpenhorn/task.py
- tests/test_queue.py
- tests/test_task.py
I think the solution for the problem outlined in #193 is to only run the "tidy-up" task when no other I/O is happening on the node.  This task is unusual in that it has the potential to modify anything on the node.  (Typically, tasks only concern themselves with a single file that they can be fairly certain no other tasks are also working on).
So here, I add the ability to flag an item in the task scheduler (i.e. the `FairMultiFIFOQueue`) as "exclusive".
* Exclusive items aren't returned by get() unless there's nothing else in-progress from its FIFO.
* When an exclusive item is returned by get(), the FMFQ locks its FIFO, preventing further items from that FIFO from being returned. The FIFO remains locked until the next task_done() call for that FIFO.
Before implementing this, I considered …
> feat(queue): Scheduling for exclusive tasks

- alpenhorn/io/default.py
The last part of the fix for the problem outlined in #193 and #194: make the tidy-up task exclusive.
Requires #194
> fix(io/default): Make the tidy-up task exclusive

- alpenhorn/io/lfs.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/util.py
- tests/conftest.py
- tests/io/test_lfs.py
- tests/io/test_lustrehsmnode.py
- tests/test_util.py
On `cedar`, at least, running `lfs hsm_restore` on a file that is already being restored causes `lfs` to wait for a very long time (~15 minutes) before returning.
This deals with that eventuality by returning a timeout error if the hsm_restore call takes more than a minute.  On timeout, alpenhorn will assume success (the idea being the timeout was due to the file restore being already in progress).
However, to guard against a false assumption, alpenhorn will retry the restore request after an hour.  This retry is now also done (but after four hours) on a successful hsm_restore request.  This is to mitigate a potential issue I've been thinking about: alpenhorn submitting a successful hsm_restore request that is later abandonned by the HSM backend before the file is restored, which has been …
> fix(io/lustrehsm): Handle timeout in hsm_restore call.

- alpenhorn/db/__init__.py
- alpenhorn/db/acquisition.py
- alpenhorn/db/archive.py
- alpenhorn/db/storage.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/server/auto_import.py
- alpenhorn/server/update.py
- pyproject.toml
- tests/db/test_acquisition.py
- tests/db/test_archive.py
- tests/db/test_storage.py
- tests/io/test_ioutil.py
- tests/io/test_ioutil_crd.py
- tests/io/test_lustrehsmnode.py
- tests/server/test_auto_import.py
- tests/server/test_update_node.py
peewee-3.17.1 has already done the work of abstracting `utcnow` and `utcfromtimestamp` for the deprecation in 3.12 for us, so let's just import those into `alpenhorn.db` and call it a day.
Closes #191
> fix(db): Deal with 3.12+ naive UTC datetimes

- alpenhorn/common/extensions.py
- alpenhorn/common/util.py
- alpenhorn/db/_base.py
- alpenhorn/server/service.py
Something I found while testing #210:
If we want db._base.threadsafe to be imported into `__init__`, it can't be a scalar (because it's going to change after the import).
Instead, make it a function.
Bonus: no need to try to import `subprocess` every time a command is run.  Just import it once at module import.
> fix(db): Fix db.threadsafe

- alpenhorn/db/storage.py
- alpenhorn/server/update.py
- tests/db/test_storage.py
Instead, they'll be skipped until someone gets around to checking the file.
Closes #211
I've replaced `StorageNode.filecopy_present` with `filecopy_state` which simply returns `('N', 'X', 'M', 'Y')` and leaves it to the caller to decide what "present" means, since the two places we were calling this function, there were different meanings.
> fix(service.update): Don't cancel AFCR for suspect files

- alpenhorn/db/storage.py
- alpenhorn/io/lfs.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/lustrequota.py
- alpenhorn/server/update.py
- tests/conftest.py
- tests/db/test_storage.py
- tests/io/test_lfs.py
- tests/io/test_lustrehsmgroup.py
- tests/io/test_lustrehsmnode.py
- tests/server/test_auto_import.py
- tests/server/test_service.py
It seems pretty clear now that `lfs` invocation should always have a timeout to guard against Lustre locking-up all our workers.  So, now use a 1-minute timeout by default in `run_lfs`.
Then, handle both `lfs quota` and `lfs hsm_state` not returning successfully.  In `StorageNode.update_avail_gb`, passing `None` now means don't update `avail.gb` (but do still update the last check time).  If the current value of `avail_gb` is not null/None, a warning is issued.
For `hsm_state` failing, various places in `LustreHSM` where it was used now handles not being able to determine the state.
Also removed an unnecessary `lfs quota` invocation from the idle update `LustreHSMNodeIO.release_files()`
I was reading through the lustre source code last night to see if I could figure out what's up with …
> fix(lfs): make HSM interactions more robust

- alpenhorn/io/_default_asyncs.py
- tests/io/test_defaultgroup.py
When the task queue is very deep, it's possible that multiple requests for the same pull can get queued.  So the group search shouldn't be surprised if the file already exists when it starts.
Closes #216
> fix(_default_asyncs): Re-check DB before transfer search

- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
- alpenhorn/server/update.py
- tests/conftest.py
- tests/io/test_defaultnode_pull.py
- tests/server/test_update_node.py
A couple of changes to reduce the amount of churn when it's taking a long time between job submission and execution because of a lot of other stuff already in the queue:
* when looking for file to ready for a remote pull, don't (re-)submit a ready job for things that are already ready (which is harmless to do, but not in any way helpful
* at the start of a pull job, re-check whether the file copy already exists on the destination node.  Again: would be harmless not to check: a new copy of the same file would overwrite the old one, but there's no harm to checking.
This takes care of the case when two pulls for the same file happen in series.  It does not solve the case of the two identical pulls occurring in parallel.
> feat(server): A few optimations for deep queues

- alpenhorn/cli/group/show.py
- alpenhorn/cli/node/__init__.py
- alpenhorn/cli/node/show.py
- alpenhorn/cli/node/stats.py
- tests/cli/group/test_show.py
- tests/cli/node/test_show.py
Also implement the `--node-stats` option to "group show"
Should the stat-generating function `get_stats` stay in `client.node.stats` or should it be moved to `client.cli` (which contains general-purpose CLI library functions)?
> feat(cli): Add "node show" command

- alpenhorn/cli/node/clean.py
- alpenhorn/daemon/update.py
- tests/cli/node/test_clean.py
- tests/daemon/test_update_node.py
Updates the daemon to try deleting any file with `has_file!='N'` (instead of just the `='Y'` ones).
The daemon will also skip trying to check files released for immediate deletion (`has_file=='N'`).
Also added `--include-bad` to CLI `node clean` command to permit manipulating `has_file` for suspect and corrupt files.
Closes #225
> feat(daemon): Permit deletion of bad files

- alpenhorn/cli/group/__init__.py
- alpenhorn/cli/group/autosync.py
- alpenhorn/cli/group/show.py
- alpenhorn/cli/node/__init__.py
- alpenhorn/cli/node/autoclean.py
- alpenhorn/cli/node/show.py
- tests/cli/group/test_autosync.py
- tests/cli/group/test_show.py
- tests/cli/node/test_autoclean.py
- tests/cli/node/test_show.py
This is based on my suggestion to remove the `action` group in #202, which I think was ill-defined.
Instead:
* Adds an `--actions` flag to `node show` and `group show` to show relevant `StorageTransferAction`s affecting the node/group.
* Adds an `--all` flag to `node show` and `group show` to provide a way to list everything without having to know what lists what.
* Adds two new commands to manipulate `StorageTransferAction`s:
* `group auto-sync GROUP NODE` to set/clear the autosync flag
* `node auto-clean NODE GROUP` to set/clear the autoclean flag
For a given (NODE, GROUP) pair, these two commands modify the same row in the `StorageTransferAction` table (the pair has to be unique in the table).  So, there's ambiguity over which command goes with which "noun". The way I've done it, the …
> feat(CLI): StorageTransferAction support

- alpenhorn/cli/cli.py
- alpenhorn/cli/group/autosync.py
- alpenhorn/cli/group/show.py
- alpenhorn/cli/node/__init__.py
- alpenhorn/cli/node/autoclean.py
- alpenhorn/cli/node/clean.py
- alpenhorn/cli/node/show.py
- alpenhorn/cli/node/verify.py
- alpenhorn/cli/options.py
- tests/cli/node/test_clean.py
- tests/cli/node/test_verify.py
This is a re-implementation of "node verify" which removes all I/O from the CLI.
As previously discussed, I think it's difficult to have I/O in the client.  In general, it's difficult to keep I/O clean unless we're
very specific on how I/O works, which we've become less-so with the new I/O framework stuff.  So, keeping I/O to the daemon vastly simplifies things.
Even with the preexisting simplified version of verification that I'm replacing, issues like #141 show how easy it is to get in to situations where verification fails.  The verify-in-cli scheme requires both running where the node is hosted and from a user that has access to the files on the node.
I don't know how we would ever run a CLI-based verify on a node like `cedar_nearline` where it would have to wait for files to be …
> fix(CLI): Re-implement "node verify"

- alpenhorn/daemon/auto_import.py
- alpenhorn/daemon/update.py
- alpenhorn/db/__init__.py
- alpenhorn/db/archive.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- tests/conftest.py
- tests/daemon/test_auto_import.py
- tests/daemon/test_entry.py
- tests/daemon/test_update_node.py
- tests/db/test_archive.py
- tests/io/test_defaultgroup.py
- tests/io/test_defaultnode.py
This adds a new table to the data index: ArchiveFileImportRequest, which contains requests for the daemon to import new file(s) into the data index.
Each request contains a node in which the import is done, a path (relative to node.root) to import, and two flags:
* recurse: whether path should be recursively scanned for files to import
* register: whether new files should be added to the data index, or whether the import should just add new ArchiveFileCopy records for pre-registered ArchiveFiles.
A third `completed` flag indicates to the daemon whether the request has been handled.
In terms of the update loop itself, there's not a whole lot to add. The `auto_import` module already has all the necessary functionality to handle these requests, and I've added a new function (`update_import`) …
> feat(daemon): Import request functionality

- alpenhorn/cli/node/__init__.py
- alpenhorn/cli/node/create.py
- alpenhorn/cli/node/init.py
- alpenhorn/daemon/auto_import.py
- alpenhorn/daemon/update.py
- alpenhorn/db/archive.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/lustrehsm.py
- tests/cli/node/test_create.py
- tests/cli/node/test_init.py
- tests/daemon/test_update_node.py
- tests/io/test_defaultnode.py
Also a --init flag to "node create" to do the same thing.
This requests the daemon intialise the node, which typically means creating the ALPENHORN_NODE file, but doesn't have to.  The request is made via the ArchiveFileImportRequest with path="ALPENHORN_NODE" (which is otherwise a forbidden path to try to import).
This has involved some changes to the daemon to give it the ability to create ALPENHORN_NODE files.  The request can't be handled in the normal part of the loop (which is skipped for uninitialised nodes), so instead it's handled during the `check_init` test in the early part of the update loop.
I've also taken the opportunity to disambiguate two different uses of the term "active" which used to be in the daemon:
* the `StorageNode.active` bit is set
* the I/O layer is ready for …
> feat(CLI): node init command

- alpenhorn/cli/acq/files.py
- alpenhorn/cli/acq/show.py
- alpenhorn/cli/node/stats.py
- alpenhorn/cli/node/verify.py
- alpenhorn/common/util.py
- tests/cli/acq/test_files.py
- tests/common/test_util.py
While it was pretty easy to avoid passing weird stuff to `pretty_bytes` in ths daemon, that's harder to do in the CLI.
I've found I've been doing the same None check a lot before using the function to deal with the potential for nulls in the database.
So, let's make the function a little more forgiving about the input. Not sure if "??? B" is the best thing to return in the None case. Let me know if you have a preference for something else.
> feat(util): Make `pretty_bytes` more forgiving

- alpenhorn/cli/acq/files.py
- alpenhorn/cli/cli.py
- alpenhorn/cli/entry.py
- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/show.py
- alpenhorn/cli/node/show.py
- alpenhorn/cli/options.py
- alpenhorn/daemon/update.py
- alpenhorn/db/archive.py
- alpenhorn/db/storage.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
- tests/cli/acq/test_files.py
- tests/cli/file/test_show.py
- tests/db/test_storage.py
I've replaced `StorageGroup.filecopy_state()` with `StorageGroup.state_on_node()` which returns both the previous status `str`, but also the node on which the copy with the state was found, which I have then added to the `acq files` table as well as using it in the new `file show`.
> feat(CLI): "file show" command

- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/create.py
- tests/cli/file/test_create.py
Not the way you should be creating ArchiveFiles, but provided for completeness (like "acq create" was).
Has some actual I/O in it: it can scan a file to generate a MD5 hash if you want it to.  Other than that, this is another simple command: it just creates an ArchiveFile record.
> feat(CLI): "file create" command

- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/sync.py
- alpenhorn/cli/options.py
- tests/cli/file/test_sync.py
Another one of the `ArchiveFileCopyRequest`-editing functions.
Allows both creating new requests for a file and cancelling exising requests for a file.  Neither is terribly involved.
Closes #64
Closes #126 (The last of the `ArchiveFileCopyRequest`-editing commands.
> feat(CLI): "file sync" command

- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/clean.py
- alpenhorn/cli/node/clean.py
- alpenhorn/cli/options.py
- tests/cli/file/test_clean.py
The first of three ArchiveFileCopy-focused commands in this group.
This one manipulates the `wants_file` column.  I've tried to make it similar to the more familiar "node clean" command.
It's quite straightforward.
> feat(CLI): "file clean" command

- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/create.py
- alpenhorn/cli/file/modify.py
- alpenhorn/cli/options.py
- tests/cli/file/test_modify.py
All this lets you do is modify the md5sum or size_b of an ArchiveFile record.
If a record is modified, by default, it will mark all the copies as needing check because we don't want to get into a situation where the has_file value is wrong.
> feat(CLI): "file modify" command

- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/list.py
- tests/cli/file/test_list.py
Usage here is a little complex.  Might need better help to explain which options can be used together.  Also: is `--not` a too confusing for the flag which negates the node/group constraint?
I found it difficult to collapse this command into a single query, so instead there are three stages (excluding the various name-to-thing look-ups):
1. one or more query to handle location and state flag constraints
2. a query, maybe, for --from and --to
3. a final query that ties the above together with the --acq limit, and applies the --not, if necessary.
Closes #45 via:
```
file list --corrupt --node=<NODE>
```
> feat(CLI): "file list" command

- alpenhorn/cli/acq/create.py
- alpenhorn/cli/file/create.py
- alpenhorn/common/util.py
- alpenhorn/daemon/auto_import.py
- alpenhorn/daemon/update.py
- tests/cli/acq/test_create.py
- tests/cli/file/test_create.py
- tests/common/test_util.py
- tests/daemon/test_auto_import.py
- tests/daemon/test_update_node.py
This creates a function, `common.util.invalid_import_path`, that takes an acq name, file name or both, and checks whether it can be used.
This is then used in four places to try to reduce the number of invalid acq/file names that make it into the database:
* in the "acq create" CLI command
* in the "file create" CLI command
* to check the acq-name returned by the import-detect extension
* when processing non-recursive ArchiveFileImportRequests
I have also added a check for recursive ArchiveFileImportRequests that the requested scan path is resolvable and in-tree.
I think it's still fairly easy to maliciously add such names to the database, but this should deal with inadvertently providing invalid names.
Closes #252
> fix(import): Vet acq and file names

- alpenhorn/cli/entry.py
- alpenhorn/common/config.py
- alpenhorn/common/util.py
- alpenhorn/daemon/entry.py
- tests/common/test_config.py
The error raised when no config files can be found will now always be ClickException and the error text now points the user to the new --help-config option which will provide basic help on what needs to be configured for things to work.  (And refer the user to the as-yet non-existent documentation for full details.)
I was originally going to only do this in the CLI, but I think it's helpful to people running the daemon to also see it there.
The --help-config option is an eager option, which means it can be used without needing the full alpenhorn start-up sequence to complete.
Closes #245
> fix(ui): Better error message for no config

- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/create.py
- alpenhorn/cli/file/find.py
- alpenhorn/cli/file/list.py
- alpenhorn/cli/group/sync.py
- alpenhorn/cli/node/clean.py
- alpenhorn/cli/node/verify.py
- alpenhorn/cli/options.py
- tests/cli/file/test_find.py
After "file list", this was less involved that I feared it would be.
I think there's potential to add more ways of searching for files, but this is good for now.  There are always going to be limits to how much selection can be done with the CLI.  For very complex queries, users are going to have to access the ORM directly and make their own queries.
This is the last command I wanted to implement from the command list in #202, unless someone can come up with an argument to promote one of the proposed commands I suggested, which otherwise will get left on the back-burner.
After all these command PRs are merged there is still going to be one or more clean-up passes to do on the CLI before I'm willing to leave it alone for the time-being.
Closes #248
> feat(CLI): "file find" command

- alpenhorn/cli/acq/__init__.py
- alpenhorn/cli/cli.py
- alpenhorn/cli/db/__init__.py
- alpenhorn/cli/entry.py
- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/group/__init__.py
- alpenhorn/cli/node/__init__.py
- alpenhorn/db/_base.py
- tests/conftest.py
My goal here was to deal with #244 but that's led me to do some general (and well-needed) clean-up of how the database connections are handled in the test suite as well.
The first thing I've done is in `alpenhorn.db._base` where I've removed the the fallback in-memory DB in the default `_connect` function which used to be instantiated when no DB connection data was present in the config.  I think this was here to make testing alpenhorn easier, but it causes trouble in production environments by hiding instances where the config is not available.
Had we required all productions systems to use a database extension for production database access, this might have been fine to leave as-is, but in practice I don't see how we can do that.
Secondly, a connection error in `db.connect()` will now …
> fix(db): Better DB-connection failure handling

- alpenhorn/cli/file/clean.py
- alpenhorn/cli/file/create.py
- alpenhorn/cli/file/modify.py
- alpenhorn/cli/group/sync.py
- alpenhorn/cli/node/sync.py
- alpenhorn/daemon/update.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
- alpenhorn/io/lfs.py
- tests/conftest.py
They don't have substitutions, so they can be just regular strings.
Oh, except for the one in `_default_asyncs.py`.  That one was just wrong.
> fix(alpenhorn): Fix f-strings

- alpenhorn/io/lustrehsm.py
- tests/io/test_lustrehsmnode.py
This adds an optional key to the I/O config JSON for LustreHSM nodes to allow specifying how long to wait between checks of in-progress HSM restores.
I still think it would be nice to have some sort of global default (see #197), but this will at give some ability to adjust the otherwise hard-coded value.
Closes #222
> feat(io): Parameterise LustreHSM restore check time

- alpenhorn/daemon/entry.py
- alpenhorn/daemon/update.py
- tests/daemon/test_entry.py
- tests/daemon/test_update.py
Adds an option -o/--once/--exit-after-update to the daemon to make it run the update loop once, wait for all tasks to finish (including deferred ones), and then exit cleanly.
The end-to-end test in `tests/daemon/test_entry.py` has been updated to use this mode (rather than what we were doing before which was using the `loop_once` fixture that co-opts the global abort).
Requires #268 to prevent the end-to-end test from taking ten minutes to complete.
Closes #230
> feat(daemon): Run-once mode

- alpenhorn/daemon/update.py
- tests/daemon/test_update_node.py
This changes the logic of the deletion part of the node update loop when a node has dropped below `min_avail_gb`.  Previously, this condition would trigger deletion of all files marked for discretionary cleaning (wants_file=='M') on the node.
With this change, now only enough files are deleted to get back over `min_avail_gb`.
In CHIME, we have hardly ever used discretionary cleaning, and I think this behaviour which I want to change is the reason.  AFAIK, the idea behind `wants_file=='M'` was to produce something like what we do on `gong`: a way to have a node with a rolling spool of recent data before it gets shipped off to an archive somewhere.  The idea is files come into the spooling node and then are sent off to an archive.  When finally archived, the copy on the spool can be marked …
> feat(daemon): Minimise discretionary cleaning

- .github/workflows/main.yml
I don't see any blockers here.
> ci: bump latest Python to 3.13

- alpenhorn/cli/file/__init__.py
- alpenhorn/cli/file/verify.py
- tests/cli/file/test_verify.py
This functionality already exists; the command:
```
alpenhorn file verify FILE NODE
```
is equivalent to:
```
alpenhorn file state --set=suspect FILE NODE
```
(mostly: `file state` can create new ArchiveFileCopy records, `file verify` cannot.)
However, I think it's more intuitive to ask users who want to re-verify a single file to use a command like this than force them to understand which state they need in `file state`.
> feat(cli): file verify command

- alpenhorn/daemon/update.py
- tests/daemon/test_update.py
This fixes two obvious `RuntimError`s where I was deleting elements from a dict while iterating it.  Both cases were triggered by deactivating nodes while the main loop was running.
This was never going to work.  Not why it took us so long to notice, but I guess we rarely deactive nodes on cedar...?
> fix(update): Fix main loop crash on node deactivation

- .github/workflows/main.yml
- alpenhorn/common/config.py
- alpenhorn/common/metrics.py
- alpenhorn/common/util.py
- alpenhorn/daemon/auto_import.py
- alpenhorn/daemon/entry.py
- alpenhorn/daemon/update.py
- alpenhorn/db/archive.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/ioutil.py
- alpenhorn/scheduler/pool.py
- alpenhorn/scheduler/queue.py
- pyproject.toml
- tests/common/test_metrics.py
- tests/daemon/test_auto_import.py
- tests/db/test_archive.py
This adds a prometheus client to the daemon which will be started if the port it should listen on is specified in the alpenhorn config.
I've added metrics here and there.  I suspect some changes will be necessary to what data is produced, but that can happen iteratively. It's difficult to know how we actually want to instrument the process without some testing.  If you see any glaring omission, feel free to suggest it.  In addition to the explicit metrics I've defined, some basic stats about the python process itself, e.g. CPU load, memory usage, &c. are automatically produced by the prom client server.
Metrics themselves are represented by a new `Metrics` class which mostly wraps `prometheus_client.Gauge` and `prometheus_client.Counter`. I've tried to make a system where we should only …
> feat(daemon): Prometheus client

- pyproject.toml
- tests/conftest.py
- tests/io/test_defaultnode.py
And by "fix" I mean delete.
This fixture was mocking `pathlib.PosixPath.stat` within the fake filesystem.  But that method has worked, by default, within the fake filesystem since `pyfakefs-5.4`.
And now `pyfakefs-5.8` has broken the implementation that we were using in the `mock_stat` fixture.
So, the solution here is to delete the fixutre and require `pyfakefs>=5.4`.
Also: since I'm messing about in the dependencies, I've dropped the `docker` dependency from the test requirements: we don't use docker for testing anymore.
> fix(tests): Fix mock_stat fixture for pyfakefs>=5.8

- alpenhorn/cli/entry.py
- alpenhorn/common/config.py
- alpenhorn/daemon/entry.py
- tests/common/test_config.py
This is not the cause of the test failures in https://github.com/chime-experiment/alpenhorn-chime/pull/5, but while debugging those failures on `wind` I discovered that installed `alpenhorn.conf` files will mess up those tests.
So we need a way to tell alpenhorn to ignore installed config files so that tests can run in isolation.
Adds a `--test-isolation` flag to both CLI and daemon that will cause alpenhorn to skip loading config from the standard paths (envar and --conf still work).  And also a function in `common.config` to accomplish the same.
Note: this is not needed in the alpenhorn test suite itself, because everything in the test suite that looks for config files runs in a fake filesystem.
> feat(common.config): Test isolation

- alpenhorn/daemon/entry.py
- alpenhorn/daemon/update.py
I think systemd is failing to restart alpenhorn on wind due to it not properly setting its exit code.
This will cause the daemon to exit with exit code 1 in all cases, except when exiting successfully after being invoked in run-once mode.
> fix(daemon): Fix daemon exit status

- alpenhorn/cli/cli.py
- alpenhorn/cli/group/sync.py
- alpenhorn/cli/node/clean.py
- alpenhorn/cli/node/sync.py
- alpenhorn/cli/node/verify.py
- alpenhorn/cli/options.py
- tests/cli/group/test_sync.py
- tests/cli/group/test_sync_cancel.py
- tests/cli/node/test_clean.py
- tests/cli/node/test_sync.py
- tests/cli/node/test_verify.py
- tests/cli/test_options.py
- tests/conftest.py
This adds a `--file-list` option to various commands to allow limiting the command to a list of ArchiveFiles specified in a text file.
The intention is that, say,
```
alpenhorn node sync cedar_nearline cedar_online --file-list=<FILE>
```
should do the same thing as
```
recall_filelist <FILE>
```
is currently doing on cedar.
Can also read from stdin (via `--file-list=-`), in which case `--check` mode will be automatically turned on if the user doesn't invoke `--force`. (Because the file-reading code will consume all the input, making it impossible for the user to interactively confirm the operation, in that case.)
The commands which accept this option are:
* `node clean`
* `node sync` (AKA `group sync`)
* `node verify`
Also: renamed the `--count` flag in `node verify` to `--check` to make …
> feat(cli): Read file list via command-line option

- alpenhorn/common/metrics.py
- alpenhorn/scheduler/pool.py
When a worker stops, this will delete the `worker_idle` child metric for that worker (i.e. deleting the metric vector from the prom data).
Closes #289
> fix(scheduler): Remove worker_idle metric for stopped workers

- alpenhorn/daemon/auto_import.py
- alpenhorn/io/lustrehsm.py
- demo/demo-script.md
- tests/daemon/test_auto_import.py
While working on the demo script, I realised it's very tricky to talk about creating files on a StorageNode which has auto-import turned on which aren't going to be imported, because, by default, `alpenhorn` has no criteria to reject certain filenames.  I've been mulling this over, and I think this is likely a good way of dealing with this idea.
This changes the daemon import to refuse to register any file whose filename starts with a leading dot.  While this does put a mild restriction on users' ability to name their data files, the benefit is there is always a portion of the namespace that can be used without worring about running afoul of alpenhorn.
As a side benefit, this removes the confusion over what a lockfile for a file with a leading dot would be;  i.e. would the lockfile for a …
> feat(auto_import): Reject files with leading dots

- alpenhorn/cli/node/show.py
- alpenhorn/cli/node/stats.py
- tests/cli/node/test_show.py
- tests/cli/node/test_stats.py
The alpenhorn-1 way to indicate no maximum size for a node was to set `StorageNode.max_total_gb` to -1.  Alpenhorn-2 made things more intuitive by using Null/None in this case, but we still need to be able to handle negative sizes from the database.
Other than `max_total_gb`, there's no reason to expect the other `..._gb` fields in the database to have a negative value, but they're all just floats, so there's nothing to prevent it, so I've added a check for all the fields.
> fix(cli): Handle negative sizes in DB

- alpenhorn/cli/node/stats.py
It appears that when (a) using a MySQL database and (b) the total size of a node is above some threshold, then the resulting total size is reported as a `decimal.Decimal` rather than a simple `int`.  In this case, the number can't be multiplied or divided by a `float`.
So, I've re-arranged this calculation and done an explicit cast to get around this.
Unfortunately, I can't seem to reproduce this using Sqlite, so I don't have a unit test for it at the momemt.  Perhaps an argument for doing a pass of the test suite with MySQL...
> fix(node stats): Handle large node totals

- alpenhorn/cli/group/sync.py
- alpenhorn/cli/node/clean.py
- alpenhorn/cli/node/sync.py
- alpenhorn/cli/node/verify.py
- alpenhorn/cli/options.py
- tests/cli/group/test_sync.py
- tests/cli/node/test_clean.py
- tests/cli/node/test_verify.py
This is an attempt to make file-list parsing a little more forgiving. Removes `node.root` from files listed in the file-list, if that is present.
For transfers, this will only allow the source `node.root` (because the destination node can't be determined by the CLI).  In cases where no node is given (e.g. `group sync --cancel --all --file-list=...`) no such path removal is attempted.
> feat(cli): Allow node.root in file-list

- alpenhorn/cli/cli.py
- alpenhorn/cli/db/__init__.py
- alpenhorn/cli/db/init.py
- alpenhorn/daemon/entry.py
- alpenhorn/db/__init__.py
- alpenhorn/db/data_index.py
- demo/demo-script.md
- tests/cli/acq/test_list.py
- tests/cli/db/test_init.py
- tests/cli/file/test_list.py
- tests/cli/group/test_list.py
- tests/cli/node/test_list.py
- tests/conftest.py
- tests/daemon/test_entry.py
- tests/db/test_data_index.py
Adds schema versioning to the database.  There's no support for schema migration (that may have to come later, if we ever change the database schema), but I think it's useful to at least set up schema version tracking before we release alpenhorn more generally.  This way, if we _do_ decide to change the database schema later at the very least users will be able to tell whether the alpenhorn they're using is compatible with the database they have.
Adds a new table, `DataIndexVersion`, with columns as outlined in #62 to track schema versioning (which can be used by extensions, if they so desire).  Also adds a new global `alpenhorn.db.current_version` containing the currently-supported schema version, which I've set to 2, leaving 1 to represent all old ("CHIME-style") data index versions. …
> feat(db): Implement schema versioning

- demo/demo-script.md
- examples/pattern_importer.py
- tests/daemon/test_entry.py
We're not going to remove support to allow extensions of the alpenhorn tables.  CHIME needs it.  (Also: peewee allows it; it would be difficult to prevent from within alpenhorn.) But, I think it's both unnecessarily confusing, and also not a demonstration of best practices, to do this in an example extension.
So, this PR replaces the extension of `ArchiveAcq` and `ArchiveFile` in the pattern exporter with a couple new tables (`AcqData` and `FileData`) to hold the extra metadata that it wants to store.
As a result of changing this I've re-ordered the steps in the demo to create the alpenhorn data index first and then initialise the extension second, which I think is a more intuitive way to do it.  I've also updated the end-to-end test of the daemon in `tests/daemon/test_entry.py` for this …
> refactor(pattern_importer): Don't extend alpenhorn tables

- alpenhorn/db/data_index.py
A quick chaser for #300... It looks like `mysql.connector` raises `ProgrammingError` when the table doesn't exist, unlike SQlite, which uses `OperationalError`, so let's handle both.
(Yet another argument for a MySQL pass on the test suite.)
> fix(schema_version): Handle peewee.ProgrammingError

- alpenhorn/cli/entry.py
- alpenhorn/cli/group/autosync.py
- alpenhorn/cli/group/sync.py
- alpenhorn/cli/node/clean.py
- alpenhorn/cli/options.py
- alpenhorn/common/config.py
- alpenhorn/common/extensions.py
- alpenhorn/common/util.py
- alpenhorn/daemon/auto_import.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/updownlock.py
- alpenhorn/scheduler/pool.py
- alpenhorn/scheduler/queue.py
`ruff`, explicitly, doesn't do type checking with type hinting, so I've experimented a bit with running `mypy` on the code to see what it would say.  The primary result is now I have Opinions on `mypy`, which this PR is too narrow to contain.  But has also found some problems that I've fixed here, which is great.  Still, I'm not convinced it's something we want running in our CI...
Most of these fixes are fixes to the type hints themselves, which is what I was expecting `mypy` to help me with, but there are a few actual (albeit minor) bugs which have also been fixed.
I also experimented in this branch with `ruff format` as a replacement for `black`.  It produces results that are very similar (by design: the `ruff` devs are overtly trying to mimic black), but it's not identical. The thing …
> Mypy / ruff format fixes

- alpenhorn/common/util.py
- tests/common/test_util.py
I still think passing a negative number to this function probably indicates a bug, but it's probably not the kind of bug we need to necessarily crash over (since this is just going to be used in a log message, after all).
> feat(common.util): Allow negative sizes in `pretty_bytes`

- alpenhorn/io/lfs.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/lustrequota.py
- tests/conftest.py
- tests/daemon/test_auto_import.py
- tests/daemon/test_entry.py
- tests/daemon/test_update.py
- tests/io/test_lfs.py
- tests/io/test_lustrehsmgroup.py
- tests/io/test_lustrehsmnode.py
- tests/io/test_lustrequota.py
Adds a new requried I/O key `quota_type` to lustrequota and lustrehsm nodes to indicate what sort of quota should be queried (user, group, project).
Also renames I/O key `quota_group` to `quota_id`.  The legacy `quota_group` I/O key is supported as an undocumented legacy extension to ease CHIME migration.
Closes #308
> feat(io.lfs): Add support for user and project quota

- alpenhorn/daemon/auto_import.py
- alpenhorn/daemon/update.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/lustrequota.py
- alpenhorn/scheduler/queue.py
- alpenhorn/scheduler/task.py
- tests/daemon/test_update.py
- tests/daemon/test_update_node.py
- tests/io/test_defaultgroup.py
- tests/io/test_ioutil_crd.py
- tests/io/test_lustrehsmgroup.py
- tests/io/test_lustrehsmnode.py
- tests/io/test_lustrequota.py
- tests/io/test_transport.py
- tests/scheduler/test_queue.py
- tests/scheduler/test_task.py
This is a four-piece (=commit) update to the daemon to deal with tasks which are left in the queue after the node/group they're targetting goes away.
That is, setting the value of the "fifo" label in the metrics generated by the queue.  This is preparation for the next piece.  The goal here is to avoid requiring the FIFO used in the queue (which can be anything hashable) to be something human-readable.
With the freedom that piece one gives us, piece 2 changes the way FIFO keys used by I/O instances to submit tasks are generated.  Now a unique FIFO will be used by each instance of an I/O class.
FIFO keys started out as just StorageNode.name.  That worked until StorageGroups also started submitting tasks, and they were distinguished by group/node.  The change here increases that …
> Dequeue tasks when stopping/reseting I/O for a node.

- demo/alpenhorn.conf
- demo/docker-compose.yaml
- doc/_static/css/alpenhorn.css
- doc/conf.py
- doc/demo.rst
- examples/pattern_importer.py
_Read this version of the demo on RTD here: https://alpenhorn.readthedocs.io/en/doctest/demo.html_
An unfortunately large fraction of the changes here are simply RST formatting fixes (and adding things like hint and tip callouts).
Important changes:
* I've rotated the background highlight for stuff occurring within the docker containers by 180 degrees in hue (meaning the background is a not-entirely-unpleasant purplish instead of yellow) with the hope that it makes it more clear where specific actions take place.
* I've added an extra container to the demo, which I've called `alpenshell` where the demo suggests you run the `alpenhorn` CLI commands (though it does point out you could use one of the storage hosts, too).  My reasoning is twofold:
* it reinforces the idea that the CLI can be …
> doc: Update demo per Josh's notes

- alpenhorn/db/_base.py
- alpenhorn/db/data_index.py
- tests/cli/db/test_init.py
This replaces the previous behaviour, which was a mountain of cascading connection error tracebacks.
> fix(db): Exit gracefully on missing database

- alpenhorn/common/metrics.py
- tests/common/test_metrics.py
Forces a "daemon" label to be bound whenever creating a metric.  The default value of this metric is the hostname we're running on (specifically, the value returned by `util.get_hostaname()`, which may be a value specified in the config file).
This is prep work for relaying metrics from cedar through the database.
Note: I've deleted the `test_unlabelled_metric` test because, with this change, alpenhorn can no longer create unlabelled metrics, meaning the test can't be performed anymore. (Support for unabelled metrics hasn't been removed from the the `metric` module).
> feat(metrics): Add "daemon" label to metrics

- alpenhorn/common/config.py
- alpenhorn/common/extensions.py
- alpenhorn/common/logger.py
- alpenhorn/common/metrics.py
- alpenhorn/common/util.py
- alpenhorn/daemon/auto_import.py
- alpenhorn/daemon/entry.py
- alpenhorn/daemon/update.py
- alpenhorn/db/_base.py
- alpenhorn/io/ioutil.py
- tests/cli/db/test_init.py
- tests/common/test_config.py
- tests/common/test_logger.py
- tests/common/test_metrics.py
- tests/conftest.py
Instead of directly accessing the `config.config` dict, this introduces a function, `common.config.get`, as the standard way off accessing the config.
The primary benefit here is that this centralises handling of missing config parameters (either by returning a default or by raising an exception) and also provides a convenient place for type checking/co-ercion of config values.
There are also specific functions for numerical types: `get_int`, `get_float` which can do bounds checking.  Also `get_bytes` which handles numbers specified with "k/M/G" suffixes (and used to be the bespoke `common.logger._max_bytes_from_config` function).
The config dict itself is renamed to `config._config` to indicate it shouldn't be accessed directly.
With this change to how the alpenhorn config is accessed, …
> refactor(config): Access config via `common.config.get`

- alpenhorn/io/default.py
With this change, the free space is only updated when it's cheap to do so (i.e. not on `LustreQuota`).  This is important because this method runs in the MainThread (when it's trying to figure out whether or not it's worth attempting a pull).
We used to only have `cedar_online`, which has comparatively few transfers into it, as a `LustreQuota` node.  But now, with the new project quota on cedar, I've switched the others nodes in project space over as well and the inefficiency here is quite noticeable in `cedar_staging`.
> fix(DefaultIO): Use fast bytes_avail calls in reserve_bytes

- alpenhorn/db/storage.py
- tests/db/test_storage.py
This adds files with `has_file='M'` to the total size for a node calculated by `StorageNode.get_total_gb`.
A downstream daemon pulling files can't always tell why transfers fail. As a result, in times of network trouble, it's not unusual for a pulling daemon to mark files it fails to transfer as suspect (`has_file="M"`). In these cases, because the file is okay and it was the network that was the problem, the upstream deamon will check the file and decide it's okay, setting `has_file` back to "Y".  The net effect is a downwards transient in the reported size of a node until the networking trouble gets resolved, which can have follow-on effects such as over-filling a node.
Because it triggers a check of the file, the `has_file="M"` state is temporary (assuming a node is being managed).  So …
> fix(StorageNode): Include suspect files in size count.

- alpenhorn/daemon/update.py
- alpenhorn/io/_default_asyncs.py
- alpenhorn/io/base.py
- alpenhorn/io/default.py
- alpenhorn/io/lustrehsm.py
- alpenhorn/io/transport.py
- tests/daemon/test_update_group.py
- tests/io/test_defaultgroup.py
- tests/io/test_lustrehsmgroup.py
- tests/io/test_transport.py
This got away from me a bit, but the goal of this PR was to fix the group pull_search so that it finds all unregistered copies of a file when running.
This means:
* in `UpdatableGroup.update_pull`, the short circuit that skipped the search when a known corrupt file copy was present in the group is removed.
* in `alpenhorn.io._default_asyncs.group_search_async`, now all nodes in the group are explicitly checked, instead of stopping the search at the first match.
* Also, now only unregistered copies found in this way will be marked for checking (`has_file='M'`) but _all_ such files are found and checked. (The previous behaviour would find at most one extant file on disk, and force-check it, regardless of what its state in the database was).
* Because the async is now directly iterating over …
> fix(group_pull_search): Find _all_ unregistered copies

- alpenhorn/common/extload.py
- alpenhorn/db/__init__.py
- alpenhorn/db/_base.py
- tests/conftest.py
The database extension used to be cached in both `common.db._base` and in `common.extload`, in slightly different forms.  This worked in practice, but was probably more confusing than necessary.
So, now the database extension only gets stored in `common.db._base`.
> fix: Don't double-cache the database extension
